apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"io.portainer.kubernetes.application.kind":"content","io.portainer.kubernetes.application.name":"teslamate","io.portainer.kubernetes.application.owner":"james","io.portainer.kubernetes.application.stack":"teslamate","io.portainer.kubernetes.application.stackid":"6"},"name":"mosquitto","namespace":"teslamate"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"mosquitto"}},"template":{"metadata":{"labels":{"app":"mosquitto"}},"spec":{"containers":[{"args":["mosquitto","-c","/mosquitto-no-auth.conf"],"image":"eclipse-mosquitto:2","name":"mosquitto","ports":[{"containerPort":1883}]}]}}}}
  creationTimestamp: 2026-01-10T18:38:55Z
  generation: 1
  labels:
    io.portainer.kubernetes.application.kind: content
    io.portainer.kubernetes.application.name: teslamate
    io.portainer.kubernetes.application.owner: james
    io.portainer.kubernetes.application.stack: teslamate
    io.portainer.kubernetes.application.stackid: "6"
  name: mosquitto
  namespace: teslamate
  uid: 588d2a50-7f64-42c1-887d-01df48aa447c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mosquitto
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - args:
            - mosquitto
            - -c
            - /mosquitto-no-auth.conf
          image: eclipse-mosquitto:2
          imagePullPolicy: IfNotPresent
          name: mosquitto
          ports:
            - containerPort: 1883
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: 2026-01-10T18:38:55Z
      lastUpdateTime: 2026-01-10T18:38:57Z
      message: ReplicaSet "mosquitto-589b476f59" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: 2026-01-19T01:41:42Z
      lastUpdateTime: 2026-01-19T01:41:42Z
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"io.portainer.kubernetes.application.kind":"content","io.portainer.kubernetes.application.name":"teslamate","io.portainer.kubernetes.application.owner":"james","io.portainer.kubernetes.application.stack":"teslamate","io.portainer.kubernetes.application.stackid":"6"},"name":"mosquitto","namespace":"teslamate"},"spec":{"ports":[{"port":1883,"targetPort":1883}],"selector":{"app":"mosquitto"}}}
  creationTimestamp: 2026-01-10T18:38:55Z
  labels:
    io.portainer.kubernetes.application.kind: content
    io.portainer.kubernetes.application.name: teslamate
    io.portainer.kubernetes.application.owner: james
    io.portainer.kubernetes.application.stack: teslamate
    io.portainer.kubernetes.application.stackid: "6"
  name: mosquitto
  namespace: teslamate
  uid: cc7ff792-c216-4e10-95c7-e11d19c90275
spec:
  clusterIP: 10.43.34.107
  clusterIPs:
    - 10.43.34.107
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 1883
      protocol: TCP
      targetPort: 1883
  selector:
    app: mosquitto
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
