apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"io.portainer.kubernetes.application.kind":"content","io.portainer.kubernetes.application.name":"teslamate","io.portainer.kubernetes.application.owner":"james","io.portainer.kubernetes.application.stack":"teslamate","io.portainer.kubernetes.application.stackid":"6"},"name":"teslamate","namespace":"teslamate"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"teslamate"}},"template":{"metadata":{"labels":{"app":"teslamate"}},"spec":{"containers":[{"env":[{"name":"ENCRYPTION_KEY","value":"oYlf5jjHx6zttMhIJi9DHVpph5rv6+B3dw3spaHV0TozQulWc3kX"},{"name":"DATABASE_USER","value":"postgres"},{"name":"DATABASE_PASS","value":"pass"},{"name":"DATABASE_NAME","value":"teslamate"},{"name":"DATABASE_HOST","value":"postgresql.db.svc.cluster.local"},{"name":"MQTT_HOST","value":"mosquitto.teslamate.svc.cluster.local"}],"image":"teslamate/teslamate:latest","name":"teslamate","ports":[{"containerPort":4000}],"securityContext":{"capabilities":{"drop":["ALL"]}},"volumeMounts":[{"mountPath":"/opt/app/import","name":"import"}]}],"volumes":[{"name":"import","persistentVolumeClaim":{"claimName":"teslamate-import"}}]}}}}
  creationTimestamp: 2026-01-10T18:38:55Z
  generation: 4
  labels:
    io.portainer.kubernetes.application.kind: content
    io.portainer.kubernetes.application.name: teslamate
    io.portainer.kubernetes.application.owner: james
    io.portainer.kubernetes.application.stack: teslamate
    io.portainer.kubernetes.application.stackid: "6"
  name: teslamate
  namespace: teslamate
  uid: da749074-6607-483a-b2d8-d254948c846c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: teslamate
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: teslamate
    spec:
      containers:
        - env:
            - name: ENCRYPTION_KEY
              value: oYlf5jjHx6zttMhIJi9DHVpph5rv6+B3dw3spaHV0TozQulWc3kX
            - name: DATABASE_USER
              value: postgres
            - name: DATABASE_PASS
              value: pass
            - name: DATABASE_NAME
              value: teslamate
            - name: DATABASE_HOST
              value: postgresql.db.svc.cluster.local
            - name: MQTT_HOST
              value: mosquitto.teslamate.svc.cluster.local
          image: teslamate/teslamate:latest
          imagePullPolicy: Always
          name: teslamate
          ports:
            - containerPort: 4000
              protocol: TCP
          resources: {}
          securityContext:
            capabilities:
              drop:
                - ALL
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/app/import
              name: import
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: import
          persistentVolumeClaim:
            claimName: teslamate-import
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: 2026-01-10T18:38:55Z
      lastUpdateTime: 2026-01-10T18:41:26Z
      message: ReplicaSet "teslamate-55575bc576" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: 2026-01-19T01:41:44Z
      lastUpdateTime: 2026-01-19T01:41:44Z
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"io.portainer.kubernetes.application.kind":"content","io.portainer.kubernetes.application.name":"teslamate","io.portainer.kubernetes.application.owner":"james","io.portainer.kubernetes.application.stack":"teslamate","io.portainer.kubernetes.application.stackid":"6"},"name":"teslamate","namespace":"teslamate"},"spec":{"ports":[{"nodePort":30400,"port":4000,"targetPort":4000}],"selector":{"app":"teslamate"},"type":"NodePort"}}
  creationTimestamp: 2026-01-10T18:38:55Z
  labels:
    io.portainer.kubernetes.application.kind: content
    io.portainer.kubernetes.application.name: teslamate
    io.portainer.kubernetes.application.owner: james
    io.portainer.kubernetes.application.stack: teslamate
    io.portainer.kubernetes.application.stackid: "6"
  name: teslamate
  namespace: teslamate
  uid: a98c3dd1-be25-4eac-a605-15632d0e74bd
spec:
  clusterIP: 10.43.94.28
  clusterIPs:
    - 10.43.94.28
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 30400
      port: 4000
      protocol: TCP
      targetPort: 4000
  selector:
    app: teslamate
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
