{
 "title": "Cluster Logs",
 "tags": [
  "loki",
  "logs",
  "kubernetes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "loki" },
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values({namespace=\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values({namespace=\"$namespace\", pod=~\"$pod\"}, container)"
   },
   { "name": "search", "label": "Search" }
  ]
 },
 "panels": [
  {
   "title": "Log Volume by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (namespace) (count_over_time({namespace=~\".+\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Logs - $namespace",
   "type": "logs",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"} |= \"$search\""
    }
   ]
  },
  {
   "title": "Errors - $namespace",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\"} |~ \"(?i)(error|fail|exception|panic|fatal)\""
    }
   ]
  }
 ]
}