# ============================================================================
# NAMESPACE
# ============================================================================

apiVersion: v1
kind: Namespace
metadata:
  name: gitea

# ============================================================================
# PERSISTENT VOLUME
# ============================================================================
# Local storage on thinkpad node for Gitea data (repos, config, etc)

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gitea-storage
  local:
    path: /srv/gitea
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - thinkpad

# ============================================================================
# PERSISTENT VOLUME CLAIM
# ============================================================================

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data
  namespace: gitea
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gitea-storage
  resources:
    requests:
      storage: 50Gi

# ============================================================================
# DEPLOYMENT
# ============================================================================
# Gitea self-hosted Git service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: gitea

spec:
  replicas: 1

  # Selector must match template labels below
  selector:
    matchLabels:
      app: gitea

  template:
    metadata:
      labels:
        app: gitea

    spec:
      # Pin to thinkpad where our PersistentVolume lives
      nodeSelector:
        kubernetes.io/hostname: thinkpad

      containers:
        - name: gitea
          image: gitea/gitea:latest
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 3000
            - name: ssh
              containerPort: 22

          env:
            # Database - uses K8s DNS: <service>.<namespace>.svc.cluster.local
            - name: GITEA__database__DB_TYPE
              value: postgres
            - name: GITEA__database__HOST
              value: postgresql.db.svc.cluster.local:5432
            - name: GITEA__database__NAME
              value: gitea
            - name: GITEA__database__USER
              value: gitea
            - name: GITEA__database__PASSWD
              value: gitea

            # Server config
            - name: GITEA__server__DOMAIN
              value: git.lab.jjh.us
            - name: GITEA__server__ROOT_URL
              value: https://git.lab.jjh.us
            - name: GITEA__server__SSH_DOMAIN
              value: git.lab.jjh.us
            - name: GITEA__server__SSH_PORT
              value: "30022"

          volumeMounts:
            - name: gitea-data
              mountPath: /data

          # Requests = guaranteed minimum, Limits = hard cap
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"

      volumes:
        - name: gitea-data
          persistentVolumeClaim:
            claimName: gitea-data

# ============================================================================
# SERVICE - HTTP
# ============================================================================
# ClusterIP = internal only, accessed via Ingress from outside

---
apiVersion: v1
kind: Service
metadata:
  name: gitea-http
  namespace: gitea
spec:
  type: ClusterIP
  selector:
    app: gitea
  ports:
    - name: http
      port: 3000
      targetPort: 3000

# ============================================================================
# SERVICE - SSH
# ============================================================================

---
apiVersion: v1
kind: Service
metadata:
  name: gitea-ssh
  namespace: gitea
spec:
  type: NodePort
  selector:
    app: gitea
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      nodePort: 30022

# ============================================================================
# INGRESS
# ============================================================================
# Traefik ingress with Let's Encrypt SSL

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea
  namespace: gitea
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    traefik.ingress.kubernetes.io/router.tls.domains.0.main: "lab.jjh.us"
    traefik.ingress.kubernetes.io/router.tls.domains.0.sans: "*.lab.jjh.us"
spec:
  tls:
    - hosts:
        - git.lab.jjh.us
  rules:
    - host: git.lab.jjh.us
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitea-http
                port:
                  number: 3000
