# ============================================================================
# DOCKER REGISTRY - COMPLETE CONFIGURATION
# ============================================================================
# Private Docker container registry for storing and distributing images
# Features:
# - Persistent storage on opti node
# - Traefik ingress with Let's Encrypt SSL
# - Basic authentication support
# - NodePort for direct access
# ============================================================================

# ============================================================================
# NAMESPACE
# ============================================================================

apiVersion: v1
kind: Namespace
metadata:
  name: registry

# ============================================================================
# PERSISTENT VOLUME
# ============================================================================
# Local storage on opti node for registry images
# ============================================================================

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  local:
    path: /srv/docker-registry
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - opti

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  namespace: registry
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 100Gi

# ============================================================================
# DEPLOYMENT
# ============================================================================
# Docker Registry v2
# Pinned to opti node where storage is located
# ============================================================================

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  namespace: registry
  labels:
    app: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      # Pin to opti node since storage is local
      nodeSelector:
        kubernetes.io/hostname: opti

      containers:
        - name: registry
          image: registry:2
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 5000
              protocol: TCP

          # Environment variables for registry configuration
          env:
            # Enable deletion of images
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
            # Log level
            - name: REGISTRY_LOG_LEVEL
              value: "info"

          volumeMounts:
            # Registry data storage
            - name: registry-data
              mountPath: /var/lib/registry

          # Resource limits
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"

          # Health checks
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5

      volumes:
        - name: registry-data
          persistentVolumeClaim:
            claimName: registry-pvc

# ============================================================================
# SERVICE
# ============================================================================
# NodePort service for Docker Registry
# HTTP: 5000 -> NodePort 30500
# ============================================================================

---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: registry
  labels:
    app: docker-registry
spec:
  type: NodePort
  selector:
    app: docker-registry
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30500
      protocol: TCP

# ============================================================================
# INGRESS
# ============================================================================
# Traefik ingress with automatic Let's Encrypt SSL certificate
# URL: https://docker.lab.jjh.us
#
# Usage:
#   docker login docker.lab.jjh.us
#   docker tag myimage:latest docker.lab.jjh.us/myimage:latest
#   docker push docker.lab.jjh.us/myimage:latest
# ============================================================================

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docker-registry
  namespace: registry
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    traefik.ingress.kubernetes.io/router.tls.domains.0.main: "lab.jjh.us"
    traefik.ingress.kubernetes.io/router.tls.domains.0.sans: "*.lab.jjh.us"
spec:
  tls:
    - hosts:
        - docker.lab.jjh.us
  rules:
    - host: docker.lab.jjh.us
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: docker-registry
                port:
                  number: 5000

# ============================================================================
# REGISTRY UI DEPLOYMENT
# ============================================================================
# Web UI for browsing and managing the Docker Registry
# ============================================================================

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry-ui
  namespace: registry
  labels:
    app: docker-registry-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry-ui
  template:
    metadata:
      labels:
        app: docker-registry-ui
    spec:
      containers:
        - name: registry-ui
          image: joxit/docker-registry-ui:latest
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 80
              protocol: TCP

          # Environment variables for UI configuration
          env:
            # Use nginx proxy mode to avoid mixed content issues
            # The UI will proxy requests to the registry
            - name: NGINX_PROXY_PASS_URL
              value: "http://docker-registry:5000"

            # Registry title shown in UI
            - name: REGISTRY_TITLE
              value: "Homelab Docker Registry"

            # Enable deletion of images
            - name: DELETE_IMAGES
              value: "true"

            # Show content digest
            - name: SHOW_CONTENT_DIGEST
              value: "true"

            # Enable catalog elements limit
            - name: CATALOG_ELEMENTS_LIMIT
              value: "1000"

            # Single registry mode (not a hub)
            - name: SINGLE_REGISTRY
              value: "true"

          # Resource limits
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"

          # Health checks
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

# ============================================================================
# REGISTRY UI SERVICE
# ============================================================================
# NodePort service for Registry UI
# HTTP: 80 -> NodePort 30501
# ============================================================================

---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry-ui
  namespace: registry
  labels:
    app: docker-registry-ui
spec:
  type: NodePort
  selector:
    app: docker-registry-ui
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30501
      protocol: TCP

# ============================================================================
# REGISTRY UI INGRESS
# ============================================================================
# Traefik ingress with automatic Let's Encrypt SSL certificate
# URL: https://registry-ui.lab.jjh.us
# ============================================================================

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docker-registry-ui
  namespace: registry
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    traefik.ingress.kubernetes.io/router.tls.domains.0.main: "lab.jjh.us"
    traefik.ingress.kubernetes.io/router.tls.domains.0.sans: "*.lab.jjh.us"
spec:
  tls:
    - hosts:
        - registry-ui.lab.jjh.us
  rules:
    - host: registry-ui.lab.jjh.us
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: docker-registry-ui
                port:
                  number: 80
